###################################
# Experiment Parameters and setup #
###################################
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref ./results/hifi_gan/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
progress_sample_path: !ref <output_folder>/samples
epochs: 300
keep_checkpoint_interval: 50
use_tensorboard: True

#################################
# Data files and pre-processing #
#################################
data_folder: !PLACEHOLDER # e.g, /datasets/LibriTTS

train_json: !ref <save_folder>/train.json
valid_json: !ref <save_folder>/valid.json
test_json: !ref <save_folder>/test.json
skip_prep: False

splits: ["train", "valid", "test"]

vctk_valid_uttids: ['p374_418_mic1',
 'p263_030_mic1',
 's5_293_mic1',
 'p275_205_mic1',
 'p259_043_mic1',
 'p252_140_mic1',
 'p226_064_mic1',
 'p329_037_mic1',
 'p284_130_mic1',
 'p265_279_mic1',
 'p360_241_mic1',
 'p301_149_mic1',
 'p280_383_mic1',
 'p250_429_mic1',
 'p341_243_mic1',
 'p239_292_mic1',
 'p233_043_mic1',
 'p231_361_mic1',
 'p257_017_mic1',
 'p363_188_mic1',
 'p264_120_mic1',
 'p254_350_mic1',
 'p334_245_mic1',
 'p237_211_mic1',
 'p264_464_mic1',
 'p232_136_mic1',
 'p323_089_mic1',
 'p253_099_mic1',
 'p333_258_mic1',
 'p267_323_mic1',
 'p364_032_mic1',
 'p257_134_mic1',
 'p285_285_mic1',
 'p232_121_mic1',
 'p232_193_mic1',
 'p283_094_mic1',
 'p340_383_mic1',
 'p246_151_mic1',
 'p232_318_mic1',
 'p274_051_mic1',
 'p295_174_mic1',
 'p262_392_mic1',
 'p303_256_mic1',
 'p230_386_mic1',
 'p334_016_mic1',
 'p360_414_mic1',
 'p282_368_mic1',
 'p285_104_mic1',
 'p265_278_mic1',
 'p226_084_mic1',
 'p275_185_mic1',
 'p263_042_mic1',
 'p288_245_mic1',
 'p280_351_mic1',
 'p299_030_mic1',
 'p292_347_mic1',
 'p264_392_mic1',
 'p334_409_mic1',
 'p267_142_mic1',
 'p246_237_mic1',
 'p317_269_mic1',
 'p232_147_mic1',
 'p376_259_mic1',
 'p310_035_mic1',
 'p229_217_mic1',
 'p361_012_mic1',
 'p267_107_mic1',
 'p295_412_mic1',
 'p271_195_mic1',
 'p252_067_mic1',
 'p258_053_mic1',
 'p374_296_mic1',
 'p265_327_mic1',
 'p266_245_mic1',
 'p241_092_mic1',
 'p250_274_mic1',
 'p316_396_mic1',
 'p282_102_mic1',
 'p300_146_mic1',
 'p228_302_mic1',
 'p334_397_mic1',
 'p313_141_mic1',
 'p243_293_mic1',
 'p229_298_mic1',
 'p268_359_mic1',
 'p240_048_mic1',
 'p334_224_mic1',
 'p243_386_mic1',
 'p330_325_mic1',
 'p333_373_mic1',
 'p263_468_mic1',
 'p230_057_mic1',
 'p237_134_mic1',
 'p253_214_mic1',
 'p251_364_mic1',
 'p268_142_mic1',
 'p257_414_mic1',
 'p272_240_mic1',
 'p247_351_mic1',
 'p263_164_mic1',
 'p260_094_mic1',
 'p251_289_mic1',
 'p229_160_mic1',
 'p362_392_mic1',
 'p278_089_mic1',
 'p269_355_mic1',
 'p288_060_mic1',
 'p336_357_mic1',
 'p323_239_mic1',
 'p274_122_mic1',
 'p258_055_mic1',
 'p273_235_mic1',
 'p259_459_mic1',
 'p257_110_mic1',
 'p285_370_mic1',
 'p295_383_mic1',
 'p301_397_mic1',
 'p300_062_mic1',
 'p330_380_mic1',
 'p364_176_mic1',
 'p360_147_mic1',
 'p249_251_mic1',
 'p274_341_mic1',
 'p239_033_mic1',
 'p288_170_mic1',
 'p293_098_mic1',
 'p307_008_mic1',
 'p270_378_mic1',
 'p230_096_mic1',
 'p233_064_mic1',
 'p286_342_mic1',
 'p329_382_mic1',
 'p262_112_mic1',
 'p376_001_mic1',
 'p333_036_mic1',
 'p227_114_mic1',
 'p330_216_mic1',
 'p292_349_mic1',
 'p310_104_mic1',
 'p299_285_mic1',
 'p244_187_mic1',
 'p232_255_mic1',
 'p260_269_mic1',
 'p286_283_mic1',
 'p275_007_mic1',
 'p263_082_mic1',
 'p239_086_mic1',
 'p273_244_mic1',
 'p227_217_mic1',
 'p250_430_mic1',
 'p252_077_mic1',
 'p254_403_mic1',
 'p270_082_mic1',
 'p272_054_mic1',
 'p241_110_mic1',
 'p246_330_mic1',
 'p268_144_mic1',
 'p269_099_mic1',
 'p297_105_mic1',
 'p269_268_mic1',
 'p244_402_mic1',
 'p341_351_mic1',
 'p285_361_mic1',
 'p275_298_mic1',
 'p306_288_mic1',
 'p298_162_mic1',
 'p298_059_mic1',
 'p257_078_mic1',
 'p237_179_mic1',
 'p279_012_mic1',
 'p264_481_mic1',
 'p271_400_mic1',
 'p312_213_mic1',
 'p330_330_mic1',
 'p360_160_mic1',
 'p237_070_mic1',
 'p265_113_mic1',
 'p311_257_mic1',
 'p317_379_mic1',
 'p306_101_mic1',
 'p316_019_mic1',
 'p272_320_mic1',
 's5_386_mic1',
 'p269_169_mic1',
 'p298_339_mic1',
 'p340_411_mic1',
 'p284_241_mic1',
 'p286_227_mic1',
 'p247_006_mic1',
 'p333_071_mic1',
 'p278_038_mic1',
 'p271_387_mic1',
 'p247_057_mic1',
 'p270_375_mic1',
 'p293_159_mic1',
 's5_301_mic1',
 'p266_358_mic1',
 'p345_061_mic1',
 'p263_429_mic1',
 'p233_226_mic1',
 'p232_263_mic1',
 'p274_410_mic1',
 'p271_118_mic1',
 'p300_118_mic1',
 'p277_376_mic1',
 'p280_304_mic1',
 'p278_279_mic1',
 'p313_256_mic1',
 'p280_365_mic1',
 'p307_209_mic1',
 'p257_035_mic1',
 'p310_156_mic1',
 'p313_268_mic1',
 'p297_135_mic1',
 'p364_304_mic1',
 'p256_293_mic1',
 'p304_007_mic1',
 'p351_244_mic1',
 'p243_011_mic1',
 'p311_192_mic1',
 'p364_046_mic1',
 'p282_100_mic1',
 'p275_191_mic1',
 'p336_408_mic1',
 'p351_199_mic1',
 'p236_407_mic1',
 'p246_206_mic1',
 'p297_390_mic1',
 'p299_339_mic1',
 'p236_183_mic1',
 'p236_119_mic1',
 'p271_200_mic1',
 'p334_219_mic1',
 'p240_361_mic1',
 'p278_168_mic1',
 'p374_190_mic1',
 'p307_236_mic1',
 'p299_156_mic1',
 'p269_196_mic1',
 'p298_117_mic1',
 'p330_236_mic1',
 'p270_232_mic1',
 'p314_176_mic1',
 'p229_215_mic1',
 'p330_181_mic1',
 'p258_299_mic1',
 'p301_058_mic1',
 'p308_402_mic1',
 'p229_381_mic1',
 'p252_108_mic1',
 'p239_384_mic1',
 'p333_305_mic1',
 'p311_382_mic1',
 'p376_373_mic1',
 'p374_404_mic1',
 'p229_275_mic1']
 
vctk_test_spk_ids: ["p261", "p225", "p294", "p347", "p238", "p234", "p248", "p335", "p245", "p326", "p302"]

################################
# Audio Parameters             #
################################
segment_size: 8192
sample_rate: 16000
hop_length: 256
win_length: 1024
n_mel_channels: 80
n_fft: 1024
mel_fmin: 0.0
mel_fmax: 8000
mel_normalized: False
power: 1
norm: "slaney"
mel_scale: "slaney"
dynamic_range_compression: True

################################
# Optimization Hyperparameters #
################################
learning_rate: 0.00002
weight_decay: 0.9999
adam_b1: 0.8
adam_b2: 0.99
batch_size: 64 #minimum 2

train_dataloader_opts:
  batch_size: !ref <batch_size>
  drop_last: False
  num_workers: 8

valid_dataloader_opts:
  batch_size: 1
  num_workers: 8

test_dataloader_opts:
  batch_size: 1
  num_workers: 8

################################
# Model Parameters and model   #
################################

# generator params
in_channels: 80
out_channels: 1

###########################################################################################################################################################
# version | resblock_type | upsample_kernel_sizes | upsample_factors | resblock_kernel_sizes | upsample_initial_channel | resblock_dilation_sizes
#    1    |      "1"      |      [16,16,4,4]      |    [8, 8, 2, 2]  |     [3, 7, 11]        |           512            | [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
#    2    |      "1"      |      [16,16,4,4]      |    [8, 8, 2, 2]  |     [3, 7, 11]        |           128            | [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
#    3    |      "2"      |       [16,16,8]       |      [8,8,4]     |       [3,5,7]         |           256            |     [[1,2], [2,6], [3,12]]
###########################################################################################################################################################
resblock_type: "1"
resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
resblock_kernel_sizes: [3, 7, 11]
upsample_kernel_sizes: [16, 16, 4, 4]
upsample_initial_channel: 512
upsample_factors: [8, 8, 2, 2]

inference_padding: 5
cond_channels: 0
conv_post_bias: True

mel_spectogram: !name:speechbrain.lobes.models.HifiGAN.mel_spectogram
  sample_rate: !ref <sample_rate>
  hop_length: !ref <hop_length>
  win_length: !ref <win_length>
  n_fft: !ref <n_fft>
  n_mels: !ref <n_mel_channels>
  f_min: !ref <mel_fmin>
  f_max: !ref <mel_fmax>
  power: !ref <power>
  normalized: !ref <mel_normalized>
  norm: !ref <norm>
  mel_scale: !ref <mel_scale>
  compression: !ref <dynamic_range_compression>

generator: !new:speechbrain.lobes.models.HifiGAN.HifiganGenerator
  in_channels: !ref <in_channels>
  out_channels: !ref <out_channels>
  resblock_type: !ref <resblock_type>
  resblock_dilation_sizes: !ref <resblock_dilation_sizes>
  resblock_kernel_sizes: !ref <resblock_kernel_sizes>
  upsample_kernel_sizes: !ref <upsample_kernel_sizes>
  upsample_initial_channel: !ref <upsample_initial_channel>
  upsample_factors: !ref <upsample_factors>
  inference_padding: !ref <inference_padding>
  cond_channels: !ref <cond_channels>
  conv_post_bias: !ref <conv_post_bias>

discriminator: !new:speechbrain.lobes.models.HifiGAN.HifiganDiscriminator

modules:
  generator: !ref <generator>
  discriminator: !ref <discriminator>

#generator loss
stft_loss: null
mseg_loss: !new:speechbrain.lobes.models.HifiGAN.MSEGLoss
feat_match_loss: !new:speechbrain.lobes.models.HifiGAN.MelganFeatureLoss
l1_spec_loss: !new:speechbrain.lobes.models.HifiGAN.L1SpecLoss
  sample_rate: !ref <sample_rate>
  hop_length: !ref <hop_length>
  win_length: !ref <win_length>
  n_mel_channels: !ref <n_mel_channels>
  n_fft: !ref <n_fft>
  n_stft: !ref <n_fft> // 2 + 1
  mel_fmin: !ref <mel_fmin>
  mel_fmax: null
  mel_normalized: !ref <mel_normalized>
  power: !ref <power>
  dynamic_range_compression: !ref <dynamic_range_compression>

generator_loss: !new:speechbrain.lobes.models.HifiGAN.GeneratorLoss
  stft_loss: !ref <stft_loss>
  stft_loss_weight: 0
  mseg_loss: !ref <mseg_loss>
  mseg_loss_weight: 1
  feat_match_loss: !ref <feat_match_loss>
  feat_match_loss_weight: 10
  l1_spec_loss: !ref  <l1_spec_loss>
  l1_spec_loss_weight: 45

#discriminator loss
msed_loss: !new:speechbrain.lobes.models.HifiGAN.MSEDLoss

discriminator_loss: !new:speechbrain.lobes.models.HifiGAN.DiscriminatorLoss
  msed_loss: !ref <msed_loss>

#optimizer
opt_class_generator: !name:torch.optim.AdamW
  lr: !ref <learning_rate>
  betas: [!ref <adam_b1>, !ref <adam_b2>]

opt_class_discriminator: !name:torch.optim.AdamW
  lr: !ref <learning_rate>
  betas: [!ref <adam_b1>, !ref <adam_b2>]

sch_class_generator: !name:torch.optim.lr_scheduler.ExponentialLR
  gamma: !ref <weight_decay>
  last_epoch: -1

sch_class_discriminator: !name:torch.optim.lr_scheduler.ExponentialLR
  gamma: !ref <weight_decay>
  last_epoch: -1

#epoch object
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
  limit: !ref <epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: !ref <train_log>

#checkpointer
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <save_folder>
  recoverables:
    generator: !ref <generator>
    discriminator: !ref <discriminator>
    counter: !ref <epoch_counter>


hifigan_model_path: !PLACEHOLDER
pretrained_separator: !new:speechbrain.utils.parameter_transfer.Pretrainer
  collect_in: !ref <save_folder>
  loadables:
    generator: !ref <generator>
    discriminator: !ref <discriminator>
  paths:
    generator: !ref <hifigan_model_path>/generator.ckpt
    discriminator: !ref <hifigan_model_path>/discriminator.ckpt